### ISSUE TITLE
Can't suppress deprecation warnings

### ISSUE THREAD

**Issue by AndrewRook** [PySport/kloppy#383]
Hi! 

First off, this package is great, thank you so much for maintaining it! 

I'm using kloppy to load Statsbomb data and I'm getting this deprecation warning when I call `statsbomb.load`:

```
  if player.position and player.position.position_id == position_id:
/.<snip>/kloppy/domain/models/common.py:238: DeprecationWarning: Call to deprecated function position (starting_position or positions should be used).
```
This warning is thrown several times per call. I'd like to suppress it as it's an internal kloppy issue and not something related to my code, however I cannot seem to do that with any of the normal Python warning control. Specifically the following does not work.

```python
with warnings.catch_warnings(action="ignore", category=DeprecationWarning):
    dataset = statsbomb.load(
        event_file, lineup_file, threesixty_file
    )
```

I **think** that the issue is that the deprecation decorator itself overrides the warnings filter itself [here](https://github.com/PySport/kloppy/blob/97ad27e41c1efa7af91c0375ff152a271ac42985/kloppy/utils.py#L115), which then executes after my context manager sets the filter to "ignore". 

Is there any way for me to suppress this warning in my code? If not, would you be open to a pull request to remove the filter inside the decorator? I imagine the big risk with doing so would be to suppress deprecation warnings in other situations where you may want to see them, but there are other options to force deprecation warnings to show (e.g. [running python in dev mode](https://docs.python.org/3/library/devmode.html#devmode))

**Comment by AndrewRook** [comment]
Alternatively, if the solution to the warning is just to change the name of the attribute to `starting_position` I'm happy to do that too, just let me know!

**Comment by probberechts** [comment]
Thank you for reporting this!

1. We've already removed the call to the deprecated function in the latest release. Upgrading to v3.16 should resolve the issue.
2. I'm not entirely sure why the warning filters are needed here. Do you remember it, @koenvo? 

https://github.com/PySport/kloppy/blob/97ad27e41c1efa7af91c0375ff152a271ac42985/kloppy/utils.py#L145-L153

**Comment by AndrewRook** [comment]
Ah yep, you're right! Sorry to bug you, feel free to close unless you want to keep it open for the warning filter bit.

**Comment by koenvo** [comment]
I had to google that code as I can remember it was borrowed from StackOverflow. And here it is: https://stackoverflow.com/questions/2536307/decorators-in-the-python-standard-lib-deprecated-specifically#40301488

**Comment by bensynapse** [comment]
Disclosure: I run Live Tennis API.

The warning-filter part still reproduces on `master` at `51dbd38`. For both `@deprecated` and `@deprecated("reason")`, two calls inside `warnings.catch_warnings(record=True)` produce two warnings even with an `ignore` filter. An `error` filter also produces warnings instead of raising, and the filter list changes after the calls.

I plan to remove the four `simplefilter` calls in the decorator and add tests for caller-selected `ignore`, `error`, `default` and `always` behavior, including filter preservation. The warning messages, category and caller location will stay the same. This addresses the remaining filter issue; the earlier internal property call is already fixed.
